server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  security:
    user:
      name: user
      password:
  datasource:
    url: jdbc:h2:mem:memDb
    driver-class-name: org.h2.Driver
    username: user
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2