server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  security:
    user:
      name: user
      password:
  datasource:
    url: jdbc:h2:mem:memDb
    driver-class-name: org.h2.Driver
    schema: classpath:/schema.sql
    username: user
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2